curl https://api.openai.com/v1/threads/thread_5OwySoM21wXjTNrAU1NaXCcZ/messages \
  -u :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 \
  -H 'Content-Type: application/json' \
  -H 'OpenAI-Beta: assistants=v1' \
  -d '{
    "role": "user",
    "content": "Glsample에서 Amount 정보를 그래프로 나타내줘.",
    "file_ids": ["file-oBDKOM5nl9GZYwwRL3ky8R0p"]
  }'